// BleControl.h - BLE fallback transport, setup/status, and safety control path.

#pragma once

#include <Arduino.h>

enum BleControlType : uint8_t {
  BLE_CTRL_PAIR = 1,
  BLE_CTRL_PAIR_RESULT = 2,
  BLE_CTRL_CLAIM_OWNER = 3,
  BLE_CTRL_OWNER_RESULT = 4,
  BLE_CTRL_RELEASE_OWNER = 5,
  BLE_CTRL_HEARTBEAT = 6,
  BLE_CTRL_RELEASE_ALL = 7,
  BLE_CTRL_STATUS_REQUEST = 8,
  BLE_CTRL_STATUS_RESPONSE = 9,
  BLE_CTRL_SCAN_WIFI = 10,
  BLE_CTRL_SCAN_WIFI_RESULT = 11,
  BLE_CTRL_SCAN_WIFI_DONE = 12,
  BLE_CTRL_SET_WIFI_CREDENTIALS = 13,
  BLE_CTRL_WIFI_CONNECT_RESULT = 14,
  BLE_CTRL_LIST_SAVED_WIFI = 15,
  BLE_CTRL_SAVED_WIFI_ENTRY = 16,
  BLE_CTRL_SAVED_WIFI_DONE = 17,
  BLE_CTRL_FORGET_WIFI = 18,
  BLE_CTRL_RESET_PAIRING = 19,
  BLE_CTRL_ERROR = 20,
  BLE_CTRL_COMMAND_RESULT = 21,
};

enum BleErrorCode : uint16_t {
  BLE_ERROR_BAD_FRAME = 1,
  BLE_ERROR_UNSUPPORTED_VERSION = 2,
  BLE_ERROR_AUTH_FAILED = 3,
  BLE_ERROR_NOT_AUTHENTICATED = 4,
  BLE_ERROR_NOT_OWNER = 5,
  BLE_ERROR_ALREADY_OWNED = 6,
  BLE_ERROR_INVALID_STATE = 7,
  BLE_ERROR_UNKNOWN_MESSAGE = 8,
  BLE_ERROR_PAYLOAD_TOO_LARGE = 9,
};

void setupBleControl();
void pollBleControl();
bool isBleControlClientConnected();
